// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MvcDatabaseApp.Data;

#nullable disable

namespace MvcDatabaseApp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251222073309_AddCategoryAndLastModifiedToProduct")]
    partial class AddCategoryAndLastModifiedToProduct
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MvcDatabaseApp.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("isActive")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Accessories",
                            CreateDate = new DateTime(2025, 12, 22, 7, 33, 4, 599, DateTimeKind.Utc).AddTicks(2611),
                            Description = "High performance HP",
                            Name = "Laptop",
                            Price = 999.99m,
                            isActive = true
                        },
                        new
                        {
                            Id = 2,
                            Category = "Electronics",
                            CreateDate = new DateTime(2025, 12, 22, 7, 33, 4, 599, DateTimeKind.Utc).AddTicks(2617),
                            Description = "well definition",
                            Name = "Hp",
                            Price = 78.99m,
                            isActive = true
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
